export default function Terms() {
  return (
    <div className="max-w-5xl mx-auto p-10 text-slate-800 leading-relaxed font-sans bg-white shadow-xl my-10 rounded-lg border border-gray-200">
      <h1 className="text-4xl font-black uppercase mb-10 italic border-b-8 border-blue-600 pb-4 text-center">
        Full Terms of Service & Legal Disclaimer
      </h1>
      
      <div className="space-y-8 text-sm md:text-base text-justify">
        
        {/* SECTION 1: THE INTERMEDIARY DISCLAIMER */}
        <div className="bg-yellow-50 p-8 border-l-8 border-yellow-500 rounded-r-2xl shadow-inner">
          <h2 className="text-2xl font-bold mb-4 text-yellow-800 uppercase">1. Platform Service Only (NO LIABILITY)</h2>
          <p className="font-bold">
            BongoBiz acts EXCLUSIVELY as an online classified advertising platform (Intermediary). We provide a digital space where independent sellers post advertisements and potential buyers can view them. 
            <br /><br />
            By using this platform, you explicitly acknowledge that BongoBiz is NOT a party to any transaction, communication, or agreement between users. We do not participate in, witness, or facilitate the actual exchange of goods, services, or money.
          </p>
        </div>

        {/* SECTION 2: DISCLAIMER OF WARRANTIES */}
        <h2 className="text-2xl font-bold border-b-2 border-gray-100 pb-2">2. Verification and Accuracy</h2>
        <p>
          BongoBiz DOES NOT verify the identity of any user (buyer or seller) nor the quality, safety, legality, or authenticity of any item or service listed. The advertisements are generated by the users, and BongoBiz has no control over their accuracy. 
          <strong> It is your absolute and sole responsibility to perform "Due Diligence" before meeting anyone or paying any money.</strong>
        </p>

        {/* SECTION 3: TOTAL EXCLUSION OF LIABILITY (THE CORE SHIELD) */}
        <div className="bg-red-50 p-8 border-l-8 border-red-600 rounded-r-2xl">
          <h2 className="text-2xl font-bold mb-4 text-red-800 uppercase">3. Total Exclusion of Liability</h2>
          <p className="font-bold text-red-900">
            UNDER NO CIRCUMSTANCES shall BongoBiz, its founder, employees, or associates be held liable for:
          </p>
          <ul className="list-disc pl-6 mt-4 space-y-3 font-semibold text-red-800">
            <li>Any financial fraud, scam, or loss of money during transactions.</li>
            <li>Any physical harm, injury, or criminal incidents occurring during face-to-face meetings.</li>
            <li>Misbehavior, harassment, or verbal/physical abuse by any user.</li>
            <li>The sale of stolen, counterfeit, or illegal goods/services.</li>
            <li>Any emotional distress or psychological impact caused by interactions on the platform.</li>
          </ul>
        </div>

        {/* SECTION 4: USER RESPONSIBILITY (THE "SONA" PART) */}
        <h2 className="text-2xl font-bold border-b-2 border-gray-100 pb-2">4. User Interaction & Risk Assumption</h2>
        <p>
          Users are strongly advised to follow the <strong>"Safety Tips"</strong> published on our website. You acknowledge that any communication (via call, WhatsApp, or meeting) is done at your own individual risk. 
          BongoBiz does not moderate private phone calls or messages. If a user provides wrong details or behaves inappropriately, the affected party must seek legal remedy through law enforcement (Police) directly. BongoBiz is not an investigative or law-enforcement body.
        </p>

        {/* SECTION 5: FRAUD AND CRIME REPORTING */}
        <h2 className="text-2xl font-bold border-b-2 border-gray-100 pb-2">5. Illegal Activities</h2>
        <p>
          The use of BongoBiz for illegal activities, including but not limited to drug trafficking, human trafficking, illegal weapon sales, or solicitation, is strictly forbidden. 
          We reserve the right to hand over all user data (including IP addresses, phone numbers, and location logs) to <strong>Governmental Authorities</strong> and <strong>Law Enforcement Agencies</strong> without prior notice to the user if a crime is reported or suspected.
        </p>

        {/* SECTION 6: THE LEGAL VENUE */}
        <h2 className="text-2xl font-bold border-b-2 border-gray-100 pb-2">6. Jurisdiction and Choice of Law</h2>
        <p>
          These Terms shall be governed by and construed in accordance with the laws of India. Any legal action, claim, or dispute against BongoBiz related to the platform’s operations must be filed exclusively in the <strong>Courts of Nadia, West Bengal, India.</strong> 
          By using BongoBiz, you waive any right to bring legal action in any other city, state, or country.
        </p>

        {/* SECTION 7: MODIFICATIONS */}
        <h2 className="text-2xl font-bold border-b-2 border-gray-100 pb-2">7. Acceptance of Terms</h2>
        <p>
          By clicking on any phone number, WhatsApp link, or viewing any ad, you signify your absolute acceptance of these terms. If you do not agree to be bound by this total waiver of liability, you must leave this website immediately.
        </p>
      </div>

      {/* FOOTER NOTE */}
      <div className="mt-12 pt-8 border-t border-gray-200 text-center text-gray-500 italic">
        Last Updated: {new Date().toLocaleDateString('en-IN')} | BongoBiz Marketplace Regulatory Compliance
      </div>
    </div>
  );
}